import re

new_figures = r"""
\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.92\textwidth]{plot1.png}
    \caption{Kinematic Handover Radius Scaling. Log-log plot of $\Rcomm$ versus IMU accelerometer bias.}
    \label{fig:plot1}
\end{figure}

The relationship between the derived critical communication handover radius ($\Rcomm$) and the IMU accelerometer bias ($\sigma_b$) was analyzed. The log-log plot in Figure \ref{fig:plot1} demonstrates that $\Rcomm$ scales inversely with the square root of the bias, adhering to the fundamental kinematic equations of motion. For consumer-grade IMUs, the allowable distance collapses to under 1 km, whereas navigation-grade IMUs provide a vast margin of safety. This scaling law was verified analytically by propagating the 2D positional error over the maximum allowable flight time.

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.92\textwidth]{phase_b_jamming_threats.png}
    \caption{RF Threat Signatures. Spectral and temporal characterization of narrowband, barrage, and follower jamming.}
    \label{fig:jamming_threats}
\end{figure}

The spectral and temporal signatures of the primary electronic warfare threats were characterized. Figure \ref{fig:jamming_threats} illustrates the distinct power spectral density profiles of narrowband, broadband barrage, and follower jamming attacks. Narrowband attacks concentrate power in a single frequency bin, creating deep localized interference, whereas barrage jammers elevate the noise floor across the entire operating band. This characterization was critical for the design of the Bayesian Electromagnetic Environment estimator, ensuring that the feature extraction pipeline correctly mapped these physical RF phenomena to their corresponding hidden Markov states.

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.85\textwidth]{cat3_validation.png}
    \caption{Extended Trajectory Validation (Category 3). Kinematic tracking performance over complex sweeping manoeuvres.}
    \label{fig:cat3_val}
\end{figure}

The performance of the navigation pipeline was evaluated under extended trajectory scenarios. The spatial paths in Figure \ref{fig:cat3_val} demonstrate the ability of the extended Kalman filter to maintain positional accuracy during complex sweeping manoeuvres. The divergence bounds remained within the theoretical covariance envelopes, confirming the numerical stability of the state transition matrices over prolonged flight times. This was verified by cross-referencing the estimated trajectory with the ground-truth deterministic path.

\begin{figure}[htbp]
    \centering
    \includegraphics[width=0.85\textwidth]{cat4b_2ray.png}
    \caption{High-Fidelity Multipath Interference (Category 4). Deterministic 2-ray reflection patterns causing deep fading nulls.}
    \label{fig:cat4_val}
\end{figure}

The environmental extensions required the validation of a highly dynamic multi-ray propagation model. Figure \ref{fig:cat4_val} captures the complex constructive and destructive interference patterns generated by ground structures. The deterministic 2-ray model creates deep fading nulls that significantly stress the Adaptive Modulation and Coding (AMC) feedback loop. The precise locations of these nulls were verified algebraically using the Fresnel reflection coefficients and the path length difference between the direct and ground-reflected rays, proving that the simulated channel fading accurately reflects physical RF phenomenology.

"""

with open('master.tex', 'r', encoding='utf-8') as f:
    tex = f.read()

# Insert before Section 4
marker = r"%  4. OUTCOMES / DISCUSSION"
if marker in tex:
    tex = tex.replace(marker, new_figures + "\n" + marker)
else:
    print("Marker not found!")

with open('master.tex', 'w', encoding='utf-8') as f:
    f.write(tex)

print("Missing figures added.")
