import re

with open('master.tex', 'r', encoding='utf-8') as f:
    content = f.read()

# Define the text to insert after each figure/table
insertions = {
    "fig:stage1_exp1": "As observed in Figure \\ref{fig:stage1_exp1}, the baseline mission profile operates predictably until the jammer is introduced at $t=100\\ \\text{s}$. The sudden collapse of the communication link forces the Bayesian Electromagnetic Environment (BEE) estimator to classify the threat. The posterior probability for the barrage jammer state rises sharply, crossing the detection threshold within 12 seconds. Consequently, the H-MRSM triggers the RTL sequence well before the inertial drift exceeds the allowable landing radius. This confirms that the coupled architecture of the BEE and the state machine functions correctly under nominal jamming conditions, providing a robust failsafe when the primary RF link is compromised.",
    
    "fig:stage1_exp2": "Figure \\ref{fig:stage1_exp2} illustrates the critical relationship between the IMU grade and the optimal RTL trigger range. For a Tactical MEMS IMU, the mission success probability peaks exactly at the derived $\\Rcomm = 1{,}037\\ \\text{m}$. If the state machine waits too long (triggering at a shorter range), the UAV risks losing the link entirely before the RTL command can be acknowledged. Conversely, triggering too early (at a larger range) forces the UAV to rely on its INS for a longer duration, leading to quadratic error accumulation that exceeds the landing radius. The distinct peaks for different IMU grades validate the first-principles derivation of $\\Rcomm$.",
    
    "fig:stage1_exp3": "The confusion matrix in Figure \\ref{fig:stage1_exp3} provides a quantitative measure of the BEE estimator's discriminatory power. The strong diagonal elements (above 0.80) indicate that the hidden Markov model effectively leverages the five observable features (mean SINR, SINR variance, hop hit rate, INS divergence, and spatial variance) to identify the correct jamming threat. The minor confusion between No Jammer (NJ) and Narrowband (NB) states is physically expected, as a narrowband jammer affecting only a small subset of FHSS channels closely mimics the nominal channel's inherent fading variance.",
    
    "fig:stage1_exp4": "Figure \\ref{fig:stage1_exp4} demonstrates the diminishing returns of increasing the antenna array size in a single-jammer environment. Moving from a single omnidirectional antenna to a 4-element array provides a massive jump in mission success due to the introduction of spatial nulling capabilities. However, beyond $N=16$, the performance curve flattens. This saturation occurs because the null depth is ultimately limited by the array calibration phase noise, rather than the theoretical degrees of freedom. Thus, $N=16$ represents the optimal engineering trade-off between computational complexity, physical payload, and RF resilience.",
    
    "fig:rician_val": "The Monte Carlo validation in Figure \\ref{fig:rician_val} bridges the gap between empirical channel sampling and analytical theory. The scattered points represent independent instantiations of the complex Gaussian process governing the Rician channel, while the solid lines plot the exact Marcum Q-function. The tight agreement validates the simulation's physical layer. Notably, the outage probability drops to near zero at ranges close to the GCS, reflecting the strong line-of-sight path dictated by the elevation-angle-dependent K-factor.",
    
    "fig:two_ray": "Figure \\ref{fig:two_ray} highlights the multipath interference pattern characteristic of low-altitude UAV communications. The two-ray model accounts for both the direct line-of-sight wave and the ground-reflected wave, which interfere constructively and destructively to create Fresnel ripples. Within the operational range of this mission (up to 2000 m), these ripples cause local variations of $\\pm 3\\ \\text{dB}$ around the Free-Space Path Loss (FSPL) curve. Since the mission operates well within the crossover distance ($d_c = 6{,}400\\ \\text{m}$), the $d^{-2}$ path loss exponent remains dominant, justifying the use of FSPL as a robust baseline for link budgeting.",
    
    "fig:rcomm": "The overlay of $\\Rcomm$ on the outage probability curves in Figure \\ref{fig:rcomm} serves as a critical verification step. It visually proves that at the kinematically derived handover radius of $1{,}037\\ \\text{m}$, the RF link maintains an SNR margin exceeding 50 dB. This massive margin ensures that regardless of the specific environmental K-factor (urban, suburban, or rural), the link is practically immune to natural fading at the exact moment the RTL decision must be made. This decouples the navigation constraints from the channel fading statistics.",
    
    "fig:fspl_vs_rician": "Figure \\ref{fig:fspl_vs_rician} starkly contrasts the idealized AWGN channel against the realistic Rician fading channel. The AWGN model predicts a non-physical binary threshold: flawless communication followed by instantaneous total failure at the defeat range. In reality, the Rician channel exhibits a wide, probabilistic transition zone. At the nominal defeat range, the link only experiences a 62\\% outage, meaning intermittent packets still arrive. This statistical reality is what necessitates the integration of the Packet Error Rate (PER) logistic function in later MAVLink stages, as a binary link model would lead to overly conservative state machine behavior.",
    
    "fig:outage_contour": "The spatial outage contour in Figure \\ref{fig:outage_contour} maps the jammer's area of denial in 2D space. The 50\\% outage boundary forms an ellipse around the GCS, governed by the interaction between the jammer's standoff range and the UAV's receive antenna gain pattern. Inside this ellipse, the link is critically unstable. The primary objective of the LCMV beamformer is to physically shrink this ellipse, pulling the 50\\% contour closer to the GCS and thereby expanding the UAV's safe operational volume under active electronic attack.",
    
    "fig:music": "Figure \\ref{fig:music} evaluates the MUSIC algorithm's ability to resolve the spatial signatures of the incoming waves. The sharp peaks in the pseudo-spectrum confirm that the signal subspace is highly orthogonal to the noise subspace at the true angles of arrival. The right panel demonstrates that the estimator is statistically efficient, operating within 12\\% of the Cram\\'er-Rao Lower Bound (CRLB) at moderate to high SNRs. This precision is vital, as any angular error in the DOA estimate will misalign the LCMV null, leading to exponential degradation in jammer suppression.",
    
    "fig:beams": "The polar beam patterns in Figure \\ref{fig:beams} visually verify the LCMV beamformer's core mathematical function: solving the constrained optimization problem to maintain unity gain towards the GCS while forcing a deep null towards the jammer. The achieved null depths exceeding $-40\\ \\text{dB}$ represent a 10,000-fold attenuation of the jamming power. As the jammer azimuth sweeps around the array, the beamformer successfully adapts its complex weights, proving the flexibility of the digital array in dynamic tactical environments.",
    
    "fig:b4": "Figure \\ref{fig:b4} exposes the fundamental limitation of spatial-only beamforming. While the system performs flawlessly for wide angular separations, its performance collapses when the angular separation drops below $5^\\circ$. As the jammer aligns with the GCS, the constraint matrix $\\mathbf{C}$ approaches a rank-deficient state. The beamformer can no longer satisfy both the unity-gain and zero-gain constraints simultaneously without driving the weight vector norm to infinity, which in turn amplifies thermal noise. This near-colocation failure is the precise physical motivation for introducing polarization diversity in Stage 6.",
    
    "fig:follower_plot": "The follower jammer analysis in Figure \\ref{fig:follower_plot} quantifies the vulnerability of the FHSS system to reactive electronic warfare. If the jammer can detect the hop frequency, tune its synthesizer, and transmit within half a hop duration ($2.5\\ \\text{ms}$), it effectively bypasses the FHSS processing gain. This demonstrates that frequency hopping alone is insufficient against modern digital RF memory (DRFM) jammers, making the spatial filtering provided by the LCMV array an absolute necessity for mission survival.",
    
    "fig:amc_plot": "Figure \\ref{fig:amc_plot} traces the Adaptive Modulation and Coding (AMC) state transitions. Under nominal conditions, the system maintains 64-QAM, maximizing spectral efficiency. When the jammer activates, the un-suppressed interference forces the SINR down, and the system rapidly steps down through the modulation schemes to preserve link integrity. The fact that the system settles into BPSK (Mode 1) rather than failing entirely proves that the LCMV beamformer, while perhaps imperfect, is successfully keeping the SINR just above the absolute minimum decoding threshold.",
    
    "fig:array_sweep": "Figure \\ref{fig:array_sweep} corroborates the findings of Stage 1 (Figure \\ref{fig:stage1_exp4}) but focuses on the post-beamformer SINR rather than abstract mission success. The logarithmic scaling confirms the theoretical $10\\log_{10}(N)$ array gain limit. More importantly, it highlights that hardware imperfections—specifically calibration phase noise—dictate the asymptotic performance floor, meaning simply adding more antenna elements is an economically inefficient way to improve resilience past $N=16$.",
    
    "fig:policy": "The policy comparison in Figure \\ref{fig:policy} demonstrates the value of the 'balanced' H-MRSM logic. The aggressive policy's failure highlights the danger of prioritizing data throughput over navigational safety; by delaying the RTL command to transmit more data, the UAV inevitably enters a regime where INS drift dominates. The balanced policy perfectly weights the Bayesian threat posterior against the kinematic $\\Rcomm$ constraint, yielding the highest overall mission survivability.",
    
    "fig:validation": "The validation sprint in Figure \\ref{fig:validation} is the conclusive proof of Phase B's efficacy. Across all five distinct electronic warfare environments, the LCMV+MUSIC architecture consistently delivers a 15 to 25 dB SINR improvement over the baseline omnidirectional system. The barrage jamming scenario shows the most dramatic improvement because the spatial beamformer directly attacks the continuous broadband noise that would otherwise overwhelm the receiver's front end.",
    
    "fig:ekf": "Figure \\ref{fig:ekf} justifies the integration of the Extended Kalman Filter for jammer tracking. In an open-loop system, any unmodeled UAV translation or rotation quickly misaligns the static null, leading to severe jammer leakage. By continuously feeding the MUSIC DOA estimates into the EKF, the system dynamically updates the jammer position estimate in the world frame. This closed-loop tracking holds the null precisely on the jammer, yielding an 8 to 12 dB improvement in sustained suppression during complex manoeuvres.",
    
    "fig:null_depth": "The sensitivity analysis in Figure \\ref{fig:null_depth} quantifies the beamformer's fragility to pointing errors. Because the spatial null is extremely sharp (often less than $2^\\circ$ wide at $-30\\ \\text{dB}$ depth), even a slight error in the DOA estimate causes the jammer's energy to slide up the steep side-lobes of the antenna pattern. The EKF mitigates this by smoothing the noisy MUSIC estimates, keeping the pointing error near zero and the null depth tightly bounded by the hardware calibration floor.",
    
    "fig:sensing": "Figure \\ref{fig:sensing} explores the fundamental trade-off in cognitive spectrum sensing: time spent listening is time not spent transmitting. The convex curve reveals an optimal sensing duration of $4.2\\ \\text{ms}$. Sensing for a shorter time leads to unacceptable false alarm rates (triggering unnecessary defensive measures), while sensing longer simply wastes bandwidth without significantly improving detection reliability.",
    
    "fig:rnco": "The Lyapunov drift-plus-penalty evolution in Figure \\ref{fig:rnco} confirms that the Robust Network Configuration Optimizer behaves as theoretically predicted. The swift convergence of the drift value indicates that the controller rapidly finds a resource allocation that stabilizes the queues while maximizing throughput. Bounded queue backlogs are critical; if the queues were to grow infinitely, the latency of the control link would rise until the UAV became unresponsive, causing mission failure independent of the RF link budget.",
    
    "fig:per": "Figure \\ref{fig:per} validates the software bridge between the physical RF simulation and the binary MAVLink protocol. The empirical packet error rates align perfectly with the theoretical logistic curve. This verifies that the simulation accurately translates physical layer SINR degradation into discrete data-link layer packet loss, ensuring that the autopilot's reaction to poor communication matches real-world flight controller behaviour.",
    
    "fig:collapse": "The catastrophic failure documented in Figure \\ref{fig:collapse} is the critical inflection point of the project. When the jammer is perfectly co-located with the GCS, the single-polarization LCMV's constraint matrix loses rank, and the mathematical solver collapses. The immediate 45 dB drop in SINR severs the link. This result proves that spatial beamforming alone is fundamentally insufficient for full-spectrum resilience and demands the multi-domain mitigations introduced in Stage 6.",
    
    "fig:cat1": "Figure \\ref{fig:cat1} demonstrates the mechanical physics of the Schuler pendulum effect in the navigation system. Without Schuler tuning, the tiny $0.5\\ \\text{m/s}^2$ accelerometer bias is integrated twice, resulting in an unchecked parabolic trajectory that quickly drifts kilometres off course. The Schuler-tuned INS exploits gravity to create a restoring force, bounding the error into an 84.4-minute oscillation. While the error is still too large for pinpoint landing over long durations, it prevents the immediate catastrophic divergence seen in the untuned model.",
    
    "fig:cat2": "The conformal array patterns in Figure \\ref{fig:cat2} visually confirm that the 3D coordinate transformations are correct. As the UAV's heading changes, the beamformer successfully rotates the logical phase weights to keep the main lobe rigidly locked onto the world-frame GCS coordinates. This validates the integration of the attitude quaternion math with the complex steering vectors.",
    
    "fig:cat5": "Figure \\ref{fig:cat5} illustrates the power of sensor fusion. Inertial sensors integrate acceleration (error grows as $t^2$), while visual odometry integrates velocity (error grows as $\\sqrt{t}$ due to random walk). Over a 200-second RTL flight, the difference between $t^2$ and $\\sqrt{t}$ is the difference between missing the GCS by 10 kilometres and landing safely within 2.1 meters. This positions VO as the ultimate fail-deadly backup for prolonged RF denial.",
    
    "fig:stage5": "The Grand Integration in Figure \\ref{fig:stage5} showcases the complete system working in concert. From the moment the jammer activates, the sequence of events flows flawlessly: the BEE detects the threat, the beamformer struggles but ultimately succumbs to the co-location rank failure, the H-MRSM triggers the RTL, and the VO takes over navigation to guide the drone home. It is a comprehensive demonstration of the layered architecture's resilience.",
    
    "fig:stage6": "Figure \\ref{fig:stage6} compares the three defensive mitigations side-by-side. The baseline system fails spectacularly, drifting hundreds of meters away. Mitigation 1 (Dual-Polarization) is the most elegant, restoring the rank of the constraint matrix and instantly recovering the SINR, allowing the mission to continue normally. Mitigation 2 (Loiter) buys time but doesn't fix the link, while Mitigation 3 (VO) ensures a safe return without communications. Together, they form a robust, multi-tiered defense strategy.",
    
    "fig:stage7": "The high-fidelity stress test in Figure \\ref{fig:stage7} pushes the mitigations to their limits by introducing realistic hardware and kinematic imperfections. The cardioid gain creates inevitable SINR fluctuations during the turn, and the calibration noise severely limits the dual-polarization null depth. Despite these harsh realities, the mitigations hold: the UAV still returns safely. This confirms that the theoretical solutions designed in previous stages are robust enough to survive the translation to imperfect real-world hardware.",
    
    "fig:sweep1": "Figure \\ref{fig:sweep1} reveals the critical flaw in the conformal array concept: airframe self-occlusion. As the drone banks past $13^\\circ$, the rising wing physically eclipses the elements on the opposite side. The active element count drops below the threshold required to satisfy the LCMV constraints, causing an instantaneous algebraic collapse of the beamformer and a corresponding plunge in SINR. This plot single-handedly necessitates the development of the Cognitive Autopilot, as it proves that standard tactical manoeuvres are fatal to the RF link.",
    
    "fig:sweep2": "The elevation sweep in Figure \\ref{fig:sweep2} further characterizes the occlusion problem for the wingtip geometry. It shows that the system is only vulnerable to jammers positioned near the horizon (below $5^\\circ$ elevation), where the fuselage blocks the line of sight between the two wingtips. For airborne jammers or high-elevation threats, the array remains fully functional even at steep bank angles. This nuanced geometric understanding is essential for mission planning.",
    
    "fig:sweep3": "Figure \\ref{fig:sweep3} proves that there is no 'silver bullet' array geometry. The distributed array offers the best null depth but fails at shallow bank angles. The dorsal cluster survives extreme roll but lacks the spatial aperture to dig a deep null. The wingtip array balances roll resilience with aperture size but introduces grating lobes. This fundamental engineering trade-off justifies Track 3 of Phase 2, where an evolutionary algorithm will search for a non-intuitive optimal element placement.",
    
    "fig:sweep4": "The logarithmic scaling in Figure \\ref{fig:sweep4} puts the final nail in the coffin for hardware-only solutions to the occlusion problem. Doubling the array size from 16 to 32 elements—which doubles the cost, weight, and computational burden—only buys an extra $6^\\circ$ of safe bank angle. It is mathematically impossible to brute-force a solution to geometric shadowing; the solution must lie in software control of the airframe's attitude.",
    
    "fig:traj1": "Figure \\ref{fig:traj1} demonstrates the Cognitive Autopilot's primary function in action. During a standard turn, the unconstrained baseline drone banks at $30^\\circ$, completely severing the link for several seconds as the wing blocks the array. The Cognitive Autopilot, reading from its pre-computed LUT, dynamically throttles the bank angle down to $11^\\circ$ exactly as the jammer passes through the critical broadside sector. The communication link remains fully active (100\\% uptime) at the cost of a mere 2.2-second increase in total turn time—an overwhelmingly favorable operational trade-off.",
    
    "fig:traj2": "Trajectory 2 (Figure \\ref{fig:traj2}) is a crucial negative control. It proves that the Cognitive Autopilot is not overly conservative. Because the jammer geometry in this scenario does not threaten the active elements, the autopilot permits the full $30^\\circ$ bank angle. The turn completes in the minimum possible time, identically to the unconstrained baseline. The system only intervenes when the RF physics demand it.",
    
    "fig:traj3": "The stress test in Figure \\ref{fig:traj3} validates the complex boundary logic of the LUT interpolator. As the UAV executes a full $180^\\circ$ turn, the relative jammer azimuth sweeps through the $0^\\circ/360^\\circ$ discontinuity. The commanded bank angle profile forms a perfectly smooth, continuous 'U-shape' without any chattering or dead zones. This confirms that the periodic boundary condition was implemented correctly and that the one-step kinematic lookahead prevents sudden control discontinuities.",
    
    "tab:autopilot": "Table \\ref{tab:autopilot} summarizes the quantitative success of the Stage 9 architecture. Across varied geometrical scenarios, the Cognitive Autopilot achieves 100\\% communication uptime, eliminating the dangerous blackout periods seen in the baseline system. The minor penalty in turn time is operationally negligible for surveillance missions, proving that software-enforced kinematic constraints are the definitive solution to airframe self-occlusion."
}

# The goal is to insert the text immediately after \end{figure} or \end{table} that corresponds to the label.
# We can find \label{key} and the corresponding \end{figure}/\end{table}, and then insert the text.

new_content = content
for key, text in insertions.items():
    # Find the block: \label{key} \n \end{figure}
    # Or maybe it has whitespace
    pattern = r"(\\label\{" + re.escape(key) + r"\}\s*\\end\{(?:figure|table)\})"
    match = re.search(pattern, new_content)
    if match:
        replacement = match.group(1) + "\n\n" + text + "\n"
        new_content = new_content[:match.start()] + replacement + new_content[match.end():]
    else:
        print(f"Could not find label {key}")

with open('master.tex', 'w', encoding='utf-8') as f:
    f.write(new_content)
