import re

with open('master.tex', 'r', encoding='utf-8') as f:
    tex = f.read()

replacements = [
    (r"We verified this by", "This was verified by"),
    (r"We generated this bar chart by", "This bar chart was generated by"),
    (r"We generated these polar plots by", "These polar plots were generated by"),
    (r"We generated these patterns by", "These patterns were generated by"),
    (r"We generated this plot using", "This plot was generated using"),
    (r"We plotted the analytical", "The analytical array factor equation was plotted"),
    (r"We fixed the target false alarm rate", "The target false alarm rate was fixed"),
    (r"We simulated a heavily loaded", "A heavily loaded network node was simulated"),
    (r"We simulated arrays ranging", "Arrays ranging from 4 to 128 elements were simulated"),
    (r"We simulated a jammer with", "A jammer with a finite reaction time was simulated"),
    (r"We ran the simulation four times", "The simulation was run four times"),
    (r"We ran the analytical expectation", "The analytical expectation was run"),
    (r"We systematically evaluated four distinct", "Four distinct geometric layouts were systematically evaluated"),
    (r"We solved the differential equations", "The differential equations were solved"),
    (r"We positioned the jammer", "The jammer was positioned"),
    (r"We passed millions of simulated", "Millions of simulated MAVLink packets were passed"),
    (r"What the plot tells us is", "What the plot indicates is"),
    (r"The plot tells us", "The plot indicates"),
    (r"We verified the", "The"),
    (r"We verified this analytically by", "This was verified analytically by"),
    (r"We verified this analytically:", "This was verified analytically:"),
    (r"We verified the 84\.4-minute period by", "The 84.4-minute period was verified by"),
    (r"We verified this geometric vulnerability by", "This geometric vulnerability was verified by"),
    (r"We verified the timing of every single event", "The timing of every single event was verified"),
    (r"We verified the success of Mitigation 1 analytically:", "The success of Mitigation 1 was verified analytically:"),
    (r"We verified the degraded null depth by", "The degraded null depth was verified by"),
    (r"We verified the array factor", "The array factor was verified"),
    (r"We verified this by", "This was verified by"),
    (r"We verified the boundary handling", "The boundary handling was verified"),
    (r"We verified these aggregate metrics by", "These aggregate metrics were verified by"),
    (r"We verified this scaling law mathematically by", "This scaling law was verified mathematically by"),
    (r"We verified the kinematic accuracy by", "The kinematic accuracy was verified by"),
    (r"We verified this", "This was verified"),
    (r"our analytical derivation", "the analytical derivation"),
    (r"our online algorithm", "the online algorithm"),
    (r"our physical-to-digital abstraction layer", "the physical-to-digital abstraction layer"),
    (r"our mitigations", "the mitigations"),
    (r"our 2000 m mission radius", "the 2000 m mission radius"),
    (r"our single-jammer model", "the single-jammer model"),
    (r"our LCMV formulation", "the LCMV formulation"),
    (r"our simulation", "the simulation")
]

for old, new in replacements:
    tex = re.sub(old, new, tex, flags=re.IGNORECASE)

# Some specific manual fixes to catch leftovers:
tex = tex.replace("The timing of every single event was verified in the chain:", "The timing of every single event in the chain was verified:")
tex = tex.replace("This was verified analytically by taking the baseline", "This was verified analytically by taking the baseline")

with open('master.tex', 'w', encoding='utf-8') as f:
    f.write(tex)

print("Pronouns removed.")
