import numpy as np
import torch
import time

def compute_oracle_steering_vectors(headings_deg, elevations_deg):
    """
    Computes true physics steering vectors by interpolating from the dense true_raytraced_grid.npz cache.
    """
    import os
    data = np.load(os.path.join(os.path.dirname(__file__), 'true_raytraced_grid.npz'))
    grid_h = data['grid_h']
    grid_e = data['grid_e']
    grid_v = data['v_true_grid']
    
    # Fill any NaNs generated by trimesh floating point errors with 1.0+0j (unshadowed)
    grid_v[np.isnan(grid_v)] = 1.0 + 0j
    
    # We use naive bilinear interpolation for the ground truth 
    # (since the true grid is dense enough that naive is acceptable for evaluation)
    # Wait, actually we can just return the vectors if we match the grid exactly, 
    # but since this is for testing, let's use phase_aware_bilinear_interpolate
    # No, wait, if we use phase_aware to GENERATE the ground truth, we are testing phase_aware against phase_aware!
    # Instead of generating test points randomly, let's just use the exact grid points?
    # Or just use nearest neighbor for the ground truth since it's very dense (0.5 deg).
    
    N = len(headings_deg)
    v_jam = np.zeros((N, 32), dtype=np.complex128)
    for i in range(N):
        idx_h = np.abs(grid_h - headings_deg[i]).argmin()
        idx_e = np.abs(grid_e - elevations_deg[i]).argmin()
        v_jam[i] = grid_v[idx_h, idx_e]
        
    # v_sig is just [1, 0, 0] in free space.
    # pos_lambda = pos_body / 0.125
    import sys
    sys.path.append(os.path.abspath(r'D:\UAV Internship project\Stage 12 (Operational Analysis)'))
    sys.path.append(os.path.abspath(r'D:\UAV Internship project\Stage 8 (Mesh Ray-Tracing)'))
    sys.path.append(os.path.abspath(r'D:\UAV Internship project\Phase 2 Track 2\array_structures'))
    from mesh_loader import load_uav_mesh
    from conformal_array import get_conformal_array_parametric
    from attitude import rotate_points, euler_to_quaternion
    from pathlib import Path
    mesh = load_uav_mesh(Path(r'D:\UAV Internship project\Stage 8 (Mesh Ray-Tracing)\assets\meshes\drone_prepared.stl'))
    pos_body, _ = get_conformal_array_parametric(mesh, N=32)
    pos_lambda = pos_body / 0.125
    
    q_inv = euler_to_quaternion(np.deg2rad(15.0), 0, 0).conjugate()
    sig_world = np.array([1.0, 0.0, 0.0])
    sig_body = rotate_points(sig_world.reshape(1, 3), q_inv)[0]
    
    theta_s = np.arccos(np.clip(sig_body[2] / np.linalg.norm(sig_body), -1.0, 1.0))
    phi_s = np.arctan2(sig_body[1], sig_body[0])
    
    dx = np.sin(theta_s) * np.cos(phi_s)
    dy = np.sin(theta_s) * np.sin(phi_s)
    dz = np.cos(theta_s)
    d = np.array([dx, dy, dz])
    
    v_sig = np.exp(1j * 2.0 * np.pi * (d @ pos_lambda.T))
    # No shadow for signal since it's from front
    
    return v_jam, v_sig

def naive_bilinear_interpolate(h, e, grid_h, grid_e, grid_v):
    """
    Interpolates complex vectors component-wise.
    h: N-array of headings
    e: N-array of elevations
    grid_h: 1D array of grid headings
    grid_e: 1D array of grid elevations
    grid_v: 3D array (len(grid_h), len(grid_e), 32) of complex vectors
    """
    N = len(h)
    out = np.zeros((N, 32), dtype=np.complex128)
    
    for i in range(N):
        idx_h = np.searchsorted(grid_h, h[i]) - 1
        idx_e = np.searchsorted(grid_e, e[i]) - 1
        
        idx_h = np.clip(idx_h, 0, len(grid_h) - 2)
        idx_e = np.clip(idx_e, 0, len(grid_e) - 2)
        
        h0, h1 = grid_h[idx_h], grid_h[idx_h+1]
        e0, e1 = grid_e[idx_e], grid_e[idx_e+1]
        
        wh = (h[i] - h0) / (h1 - h0)
        we = (e[i] - e0) / (e1 - e0)
        
        v00 = grid_v[idx_h, idx_e]
        v10 = grid_v[idx_h+1, idx_e]
        v01 = grid_v[idx_h, idx_e+1]
        v11 = grid_v[idx_h+1, idx_e+1]
        
        v_interp = (1-wh)*(1-we)*v00 + wh*(1-we)*v10 + (1-wh)*we*v01 + wh*we*v11
        out[i] = v_interp
        
    return out

def phase_aware_bilinear_interpolate(h, e, grid_h, grid_e, grid_v):
    """
    Interpolates magnitude and unwrapped phase separately.
    """
    N = len(h)
    out = np.zeros((N, 32), dtype=np.complex128)
    
    mag_grid = np.abs(grid_v)
    phase_grid = np.angle(grid_v)
    
    for i in range(N):
        idx_h = np.searchsorted(grid_h, h[i]) - 1
        idx_e = np.searchsorted(grid_e, e[i]) - 1
        
        idx_h = np.clip(idx_h, 0, len(grid_h) - 2)
        idx_e = np.clip(idx_e, 0, len(grid_e) - 2)
        
        h0, h1 = grid_h[idx_h], grid_h[idx_h+1]
        e0, e1 = grid_e[idx_e], grid_e[idx_e+1]
        
        wh = (h[i] - h0) / (h1 - h0)
        we = (e[i] - e0) / (e1 - e0)
        
        # Magnitude interpolation
        m00 = mag_grid[idx_h, idx_e]
        m10 = mag_grid[idx_h+1, idx_e]
        m01 = mag_grid[idx_h, idx_e+1]
        m11 = mag_grid[idx_h+1, idx_e+1]
        m_interp = (1-wh)*(1-we)*m00 + wh*(1-we)*m10 + (1-wh)*we*m01 + wh*we*m11
        
        # Phase interpolation requires unwrapping relative to v00
        p00 = phase_grid[idx_h, idx_e]
        
        # Function to minimize wrap distance to p00
        def unwrap_rel(p):
            diff = p - p00
            diff = (diff + np.pi) % (2 * np.pi) - np.pi
            return p00 + diff
            
        p10 = unwrap_rel(phase_grid[idx_h+1, idx_e])
        p01 = unwrap_rel(phase_grid[idx_h, idx_e+1])
        p11 = unwrap_rel(phase_grid[idx_h+1, idx_e+1])
        
        p_interp = (1-wh)*(1-we)*p00 + wh*(1-we)*p10 + (1-wh)*we*p01 + wh*we*p11
        
        out[i] = m_interp * np.exp(1j * p_interp)
        
    return out

def compute_sinr_from_v(v_pred_list, v_true_list, v_sig):
    P_J = 10000.0
    P_S = 100.0
    sigma2 = 1.0
    alpha = 390.0
    
    sinrs = []
    
    import torch
    v_sig_t = torch.tensor(v_sig, dtype=torch.complex128)
    R_sig = P_S * torch.outer(v_sig_t, torch.conj(v_sig_t))
    R_n = sigma2 * torch.eye(32, dtype=torch.complex128)
    R_sn = R_sig + R_n
    
    for v_pred, v_true in zip(v_pred_list, v_true_list):
        vp_t = torch.tensor(v_pred, dtype=torch.complex128)
        vt_t = torch.tensor(v_true, dtype=torch.complex128)
        
        # Analytic MVDR from predicted v
        R_j_pred = P_J * torch.outer(vp_t, torch.conj(vp_t))
        R_in_pred = R_j_pred + (sigma2 + alpha) * torch.eye(32, dtype=torch.complex128)
        R_in_pred_inv = torch.linalg.inv(R_in_pred)
        
        w = R_in_pred_inv @ v_sig_t
        w = w / (torch.conj(v_sig_t) @ w)
        
        # Evaluate SINR on TRUE v
        S = torch.real(torch.conj(w) @ R_sn @ w)
        NJ = P_J * torch.abs(torch.conj(w) @ vt_t)**2 + sigma2 * torch.real(torch.conj(w) @ w)
        
        sinrs.append(10 * np.log10(float(S / NJ)))
        
    return np.array(sinrs)

def test_resolution(grid_res, test_h, test_e, test_v, v_sig):
    grid_h = np.arange(170.0, 190.0 + 1e-5, grid_res)
    grid_e = np.arange(-25.0, 25.0 + 1e-5, grid_res)
    
    # Compute ground truth for grid nodes
    H_grid, E_grid = np.meshgrid(grid_h, grid_e, indexing='ij')
    flat_h_grid = H_grid.flatten()
    flat_e_grid = E_grid.flatten()
    
    grid_v_flat, _ = compute_oracle_steering_vectors(flat_h_grid, flat_e_grid)
    grid_v = grid_v_flat.reshape(len(grid_h), len(grid_e), 32)
    
    print(f"\n--- Testing Grid Resolution: {grid_res} deg (Nodes: {len(flat_h_grid)}) ---")
    
    v_interp_naive = naive_bilinear_interpolate(test_h, test_e, grid_h, grid_e, grid_v)
    sinrs_naive = compute_sinr_from_v(v_interp_naive, test_v, v_sig)
    print(f"Naive Interpolation -> Min SINR: {np.min(sinrs_naive):.2f} dB, Below 15dB: {np.sum(sinrs_naive < 15.0)}")
    
    v_interp_phase = phase_aware_bilinear_interpolate(test_h, test_e, grid_h, grid_e, grid_v)
    sinrs_phase = compute_sinr_from_v(v_interp_phase, test_v, v_sig)
    print(f"Phase Interpolation -> Min SINR: {np.min(sinrs_phase):.2f} dB, Below 15dB: {np.sum(sinrs_phase < 15.0)}")

def main():
    print("Generating dense 0.1 deg test set over 170-190, +/-25...")
    test_h = np.random.uniform(170.1, 189.9, 5000)
    test_e = np.random.uniform(-24.9, 24.9, 5000)
    
    test_v, v_sig = compute_oracle_steering_vectors(test_h, test_e)
    
    # Test Oracles on their own true vectors (should be perfect)
    oracle_sinrs = compute_sinr_from_v(test_v, test_v, v_sig)
    print(f"Perfect Oracle Min SINR: {np.min(oracle_sinrs):.2f} dB")
    
    test_resolution(1.0, test_h, test_e, test_v, v_sig)
    test_resolution(0.5, test_h, test_e, test_v, v_sig)
    
if __name__ == '__main__':
    main()
